[project]
name = "stoma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.0",
    "playwright>=1.55.0",
    "pytest>=8.4.2",
    "requests>=2.32.5",
    "openapi-pydantic>=0.5.1",
]
